//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string legal_name { get; set; }
        public string legal_surname { get; set; }
        public string print_name { get; set; }
        public int ssn { get; set; }
        public string gender { get; set; }
        public System.DateTime date_birth { get; set; }
        public string marital_status { get; set; }
        public bool us_citizen { get; set; }
        public string ethnicity { get; set; }
        public bool active { get; set; }
        public bool disability { get; set; }
        public string disability_description { get; set; }
        public bool i9_form { get; set; }
        public System.DateTime work_expires { get; set; }
        public bool us_veteran { get; set; }
        public string veteran_status { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string e_city { get; set; }
        public string e_state_province { get; set; }
        public string e_postal_code { get; set; }
        public string e_phone_number { get; set; }
        public string e_mobile_number { get; set; }
        public string e_email { get; set; }
        public string e_contact_name1 { get; set; }
        public string e_contact_phone1 { get; set; }
        public string e_contact_relation1 { get; set; }
        public string e_contact_name2 { get; set; }
        public string e_contact_phone2 { get; set; }
        public string e_contact_relation2 { get; set; }
        public Nullable<int> type { get; set; }
    }
}
