//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class entry_product
    {
        public int id { get; set; }
        public string number { get; set; }
        public System.DateTime date { get; set; }
        public int id_product { get; set; }
        public int quant { get; set; }
        public Nullable<int> id_provider { get; set; }
        public string user_name { get; set; }
    
        public virtual product product { get; set; }
        public virtual provider provider { get; set; }
    }
}
