//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_stock
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int id_product { get; set; }
        public int storage_quant { get; set; }
        public int quant_inventory { get; set; }
        public string reason { get; set; }
    
        public virtual product product { get; set; }
    }
}
