//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<entry_product> entry_product { get; set; }
        public virtual DbSet<inventory_stock> inventory_stock { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_brand> product_brand { get; set; }
        public virtual DbSet<product_group> product_group { get; set; }
        public virtual DbSet<product_output> product_output { get; set; }
        public virtual DbSet<provider> provider { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<storage_location> storage_location { get; set; }
        public virtual DbSet<unit_measure> unit_measure { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
