//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public provider()
        {
            this.entry_product = new HashSet<entry_product>();
            this.product = new HashSet<product>();
            this.product_output = new HashSet<product_output>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string corporate_name { get; set; }
        public string doc_num { get; set; }
        public int type { get; set; }
        public string phone { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public string number { get; set; }
        public string instruction { get; set; }
        public string postal_code { get; set; }
        public int id_country { get; set; }
        public int id_province { get; set; }
        public int id_city { get; set; }
        public bool active { get; set; }
    
        public virtual city city { get; set; }
        public virtual country country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entry_product> entry_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_output> product_output { get; set; }
        public virtual province province { get; set; }
    }
}
